export enum IconCategoryEnum {
  GENERAL = 'GENERAL',
  ACTION = 'ACTION',
  ARROW_AND_CARET = 'ARROW_AND_CARET',
  FILE_TYPES = 'FILE_TYPES',
  DEFAULT_STATUS = 'DEFAULT_STATUS',
  SNAPPABLE_BRAND = 'SNAPPABLE_BRAND',
  GROUP = 'GROUP',
  ROOM = 'ROOM',
}
